spring:
  datasource:
    url: jdbc:mysql://localhost:3306/migration?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: User12345!
  liquibase:
    contexts: prod
  sql:
    init:
      mode: never